<div class="sidebar col-lg-2">
			
	<nav>	
		<ul>
	
			<li class="profile">
	
		            <img class="profile-img" src="img/icon-user.png" />
	        	    <br/>
	 	            Bem Vindo
	
		        </li>

			
			<li>
				<a href="index.php" class="nav-item">
					Home
				</a>
			</li>
				
			<li>
				<a href="novo.php" class="nav-item">
					Cadastrar
				</a>
			</li>

			<li>
				<a href="consultar.php" class="nav-item">
					Consultar
				</a>
			</li>

		</ul>
	</nav>

	<span class="shadows"></span>

</div>