<div class="sidebar col-lg-2">
			
	<nav>	
		<ul>
	
			<li class="profile">

	            <img class="profile-img" src="img/icon-user.png" alt=""/>
	            <br/>
	            Bem Vindo

	        </li>

			<a href="index.php">
				
				<li class="nav-item">
					Home
				</li>
				
			</a>

			<a href="novo.php">
				
				<li class="nav-item">
					Cadastrar
				</li>
				
			</a>

			<a href="consultar.php">
				
				<li class="nav-item">
					Consultar
				</li>
				
			</a>

		</ul>
	</nav>

	<span class="shadows"></span>

</div>